<?php


 function autoload_3bbe6080c1add3551ae900bc9ce6e9a2($class)
{
    $classes = array(
        'jRazer\Wooppay\WSDL\XmlControllerServiceCustom' => __DIR__ .'/XmlControllerServiceCustom.php',
        'jRazer\Wooppay\WSDL\CoreLoginRequestCustom' => __DIR__ .'/CoreLoginRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreLoginResponseCustom' => __DIR__ .'/CoreLoginResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreLoginResponseDataCustom' => __DIR__ .'/CoreLoginResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\stringArrayCustom' => __DIR__ .'/stringArrayCustom.php',
        'jRazer\Wooppay\WSDL\CoreLogoutRequestCustom' => __DIR__ .'/CoreLogoutRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreLogoutResponseCustom' => __DIR__ .'/CoreLogoutResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreSmthRequestCustom' => __DIR__ .'/CoreSmthRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreSmthResponseCustom' => __DIR__ .'/CoreSmthResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateOperationRequestCustom' => __DIR__ .'/CashCreateOperationRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateOperationResponseCustom' => __DIR__ .'/CashCreateOperationResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateOperationResponseDataCustom' => __DIR__ .'/CashCreateOperationResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashConfirmOperationRequestCustom' => __DIR__ .'/CashConfirmOperationRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashConfirmOperationResponseCustom' => __DIR__ .'/CashConfirmOperationResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashConfirmOperationExtRequestCustom' => __DIR__ .'/CashConfirmOperationExtRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashDischargementRequestCustom' => __DIR__ .'/CashDischargementRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashDischargementResponseCustom' => __DIR__ .'/CashDischargementResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashTransferRequestCustom' => __DIR__ .'/CashTransferRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashTransferResponseCustom' => __DIR__ .'/CashTransferResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetTransfersRequestCustom' => __DIR__ .'/CashGetTransfersRequestCustom.php',
        'jRazer\Wooppay\WSDL\intArrayCustom' => __DIR__ .'/intArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashGetTransfersResponseCustom' => __DIR__ .'/CashGetTransfersResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetTransfersResponseDataCustom' => __DIR__ .'/CashGetTransfersResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetTransfersResponseDataRecordArrayCustom' => __DIR__ .'/CashGetTransfersResponseDataRecordArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashGetTransfersResponseDataRecordCustom' => __DIR__ .'/CashGetTransfersResponseDataRecordCustom.php',
        'jRazer\Wooppay\WSDL\CashGetTransfersResponseDataRecordServiceCustom' => __DIR__ .'/CashGetTransfersResponseDataRecordServiceCustom.php',
        'jRazer\Wooppay\WSDL\CashGetCommissionRequestCustom' => __DIR__ .'/CashGetCommissionRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetCommissionResponseCustom' => __DIR__ .'/CashGetCommissionResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetCommissionResponseDataCustom' => __DIR__ .'/CashGetCommissionResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CoreGetServiceIDByNameRequestCustom' => __DIR__ .'/CoreGetServiceIDByNameRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreGetServiceIDByNameResponseCustom' => __DIR__ .'/CoreGetServiceIDByNameResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreGetServiceIDByNameResponseDataCustom' => __DIR__ .'/CoreGetServiceIDByNameResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetBalanceRequestCustom' => __DIR__ .'/CashGetBalanceRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetBalanceResponseCustom' => __DIR__ .'/CashGetBalanceResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetBalanceResponseDataCustom' => __DIR__ .'/CashGetBalanceResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesRequestCustom' => __DIR__ .'/ServiceGetCategoriesRequestCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesResponseCustom' => __DIR__ .'/ServiceGetCategoriesResponseCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesResponseDataCustom' => __DIR__ .'/ServiceGetCategoriesResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesResponseDataCategoriesArrayCustom' => __DIR__ .'/ServiceGetCategoriesResponseDataCategoriesArrayCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesResponseDataCategoriesCustom' => __DIR__ .'/ServiceGetCategoriesResponseDataCategoriesCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesResponseDataServicesArrayCustom' => __DIR__ .'/ServiceGetCategoriesResponseDataServicesArrayCustom.php',
        'jRazer\Wooppay\WSDL\ServiceGetCategoriesResponseDataServicesCustom' => __DIR__ .'/ServiceGetCategoriesResponseDataServicesCustom.php',
        'jRazer\Wooppay\WSDL\CashDeclineRequestCustom' => __DIR__ .'/CashDeclineRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashDeclineResponseCustom' => __DIR__ .'/CashDeclineResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashSetOperationsStatusRequestCustom' => __DIR__ .'/CashSetOperationsStatusRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashSetOperationsStatusRequestRecordArrayCustom' => __DIR__ .'/CashSetOperationsStatusRequestRecordArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashSetOperationsStatusRequestRecordCustom' => __DIR__ .'/CashSetOperationsStatusRequestRecordCustom.php',
        'jRazer\Wooppay\WSDL\CashSetOperationsStatusResponseCustom' => __DIR__ .'/CashSetOperationsStatusResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashSetOperationsStatusResponseRecordArrayCustom' => __DIR__ .'/CashSetOperationsStatusResponseRecordArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashSetOperationsStatusResponseRecordCustom' => __DIR__ .'/CashSetOperationsStatusResponseRecordCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationsStatusRequestCustom' => __DIR__ .'/CashGetOperationsStatusRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationsStatusResponseCustom' => __DIR__ .'/CashGetOperationsStatusResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationsStatusResponseRecordArrayCustom' => __DIR__ .'/CashGetOperationsStatusResponseRecordArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationsStatusResponseRecordCustom' => __DIR__ .'/CashGetOperationsStatusResponseRecordCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutRequestCustom' => __DIR__ .'/CashCashOutRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutResponseCustom' => __DIR__ .'/CashCashOutResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutResponseDataCustom' => __DIR__ .'/CashCashOutResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutCompleteRequestCustom' => __DIR__ .'/CashCashOutCompleteRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutCompleteResponseCustom' => __DIR__ .'/CashCashOutCompleteResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutInputDataRequestCustom' => __DIR__ .'/CashCashOutInputDataRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCashOutInputDataResponseCustom' => __DIR__ .'/CashCashOutInputDataResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashReturnRequestCustom' => __DIR__ .'/CashReturnRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashReturnResponseCustom' => __DIR__ .'/CashReturnResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashReturnPartialRequestCustom' => __DIR__ .'/CashReturnPartialRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashReturnPartialResponseCustom' => __DIR__ .'/CashReturnPartialResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashMobileRefundRequestCustom' => __DIR__ .'/CashMobileRefundRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashMobileRefundResponseCustom' => __DIR__ .'/CashMobileRefundResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreUserSearchRequestCustom' => __DIR__ .'/CoreUserSearchRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreUserSearchResponseCustom' => __DIR__ .'/CoreUserSearchResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreUserSearchResponseDataCustom' => __DIR__ .'/CoreUserSearchResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\SystemGetConfigRequestCustom' => __DIR__ .'/SystemGetConfigRequestCustom.php',
        'jRazer\Wooppay\WSDL\SystemGetConfigResponseCustom' => __DIR__ .'/SystemGetConfigResponseCustom.php',
        'jRazer\Wooppay\WSDL\SystemGetConfigResponseDataCustom' => __DIR__ .'/SystemGetConfigResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashRequestTransferRequestCustom' => __DIR__ .'/CashRequestTransferRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashRequestTransferResponseCustom' => __DIR__ .'/CashRequestTransferResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashRequestTransferResponseDataCustom' => __DIR__ .'/CashRequestTransferResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashInvoicingRequestCustom' => __DIR__ .'/CashInvoicingRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashInvoicingResponseCustom' => __DIR__ .'/CashInvoicingResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashInvoicingResponseDataCustom' => __DIR__ .'/CashInvoicingResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetServiceFieldsRequestCustom' => __DIR__ .'/CashGetServiceFieldsRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetServiceFieldsResponseCustom' => __DIR__ .'/CashGetServiceFieldsResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetServiceFieldsResponseDataCustom' => __DIR__ .'/CashGetServiceFieldsResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetServiceFieldsExtendedRequestCustom' => __DIR__ .'/CashGetServiceFieldsExtendedRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCheckServiceFieldsRequestCustom' => __DIR__ .'/CashCheckServiceFieldsRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCheckServiceFieldsResponseCustom' => __DIR__ .'/CashCheckServiceFieldsResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCheckServiceFieldsResponseDataCustom' => __DIR__ .'/CashCheckServiceFieldsResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationReceiptRequestCustom' => __DIR__ .'/CashGetOperationReceiptRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationReceiptResponseCustom' => __DIR__ .'/CashGetOperationReceiptResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationReceiptResponseDataCustom' => __DIR__ .'/CashGetOperationReceiptResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataRequestCustom' => __DIR__ .'/CashGetOperationDataRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataResponseCustom' => __DIR__ .'/CashGetOperationDataResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataResponseDataCustom' => __DIR__ .'/CashGetOperationDataResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataResponseDataRecordArrayCustom' => __DIR__ .'/CashGetOperationDataResponseDataRecordArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataResponseDataRecordCustom' => __DIR__ .'/CashGetOperationDataResponseDataRecordCustom.php',
        'jRazer\Wooppay\WSDL\CoreUserExistsRequestCustom' => __DIR__ .'/CoreUserExistsRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreUserExistsResponseCustom' => __DIR__ .'/CoreUserExistsResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceRequestCustom' => __DIR__ .'/CashCreateInvoiceRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceResponseCustom' => __DIR__ .'/CashCreateInvoiceResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceResponseDataCustom' => __DIR__ .'/CashCreateInvoiceResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceExtendedRequestCustom' => __DIR__ .'/CashCreateInvoiceExtendedRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceExtended2RequestCustom' => __DIR__ .'/CashCreateInvoiceExtended2RequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceByServiceRequestCustom' => __DIR__ .'/CashCreateInvoiceByServiceRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashCreateInvoiceWithCurrencyRequestCustom' => __DIR__ .'/CashCreateInvoiceWithCurrencyRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardPerformRequestCustom' => __DIR__ .'/CashPrepaidCardPerformRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardPerformResponseCustom' => __DIR__ .'/CashPrepaidCardPerformResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardPerformResponseDataCustom' => __DIR__ .'/CashPrepaidCardPerformResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardRequestCustom' => __DIR__ .'/CashPrepaidCardRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardRequestDataCustom' => __DIR__ .'/CashPrepaidCardRequestDataCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardResponseCustom' => __DIR__ .'/CashPrepaidCardResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardResponseDataCustom' => __DIR__ .'/CashPrepaidCardResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardCommissionRequestCustom' => __DIR__ .'/CashPrepaidCardCommissionRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardCommissionResponseCustom' => __DIR__ .'/CashPrepaidCardCommissionResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashPrepaidCardCommissionResponseDataCustom' => __DIR__ .'/CashPrepaidCardCommissionResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CreateOperationCustom' => __DIR__ .'/CreateOperationCustom.php',
        'jRazer\Wooppay\WSDL\CreateOperationResponseCustom' => __DIR__ .'/CreateOperationResponseCustom.php',
        'jRazer\Wooppay\WSDL\CreateOperationRequestCustom' => __DIR__ .'/CreateOperationRequestCustom.php',
        'jRazer\Wooppay\WSDL\PayConfirmRequestCustom' => __DIR__ .'/PayConfirmRequestCustom.php',
        'jRazer\Wooppay\WSDL\PayTransferConfirmRequestCustom' => __DIR__ .'/PayTransferConfirmRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreRequestConfirmationCodeRequestCustom' => __DIR__ .'/CoreRequestConfirmationCodeRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreRequestConfirmationCodeResponseCustom' => __DIR__ .'/CoreRequestConfirmationCodeResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreBeelineSMSNotificationRequestCustom' => __DIR__ .'/CoreBeelineSMSNotificationRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreBeelineSMSNotificationResponseCustom' => __DIR__ .'/CoreBeelineSMSNotificationResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreKcellSMSNotificationRequestCustom' => __DIR__ .'/CoreKcellSMSNotificationRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreKcellSMSNotificationResponseCustom' => __DIR__ .'/CoreKcellSMSNotificationResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetReceiptForTransactionRequestCustom' => __DIR__ .'/CashGetReceiptForTransactionRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetReceiptForTransactionResponseCustom' => __DIR__ .'/CashGetReceiptForTransactionResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetReceiptForTransactionResponseDataCustom' => __DIR__ .'/CashGetReceiptForTransactionResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CoreGetMobileOperatorRequestCustom' => __DIR__ .'/CoreGetMobileOperatorRequestCustom.php',
        'jRazer\Wooppay\WSDL\CoreGetMobileOperatorResponseCustom' => __DIR__ .'/CoreGetMobileOperatorResponseCustom.php',
        'jRazer\Wooppay\WSDL\CoreGetMobileOperatorResponseDataCustom' => __DIR__ .'/CoreGetMobileOperatorResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataExtendedRequestCustom' => __DIR__ .'/CashGetOperationDataExtendedRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataExtendedResponseCustom' => __DIR__ .'/CashGetOperationDataExtendedResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataExtendedResponseDataCustom' => __DIR__ .'/CashGetOperationDataExtendedResponseDataCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataExtendedResponseDataRecordArrayCustom' => __DIR__ .'/CashGetOperationDataExtendedResponseDataRecordArrayCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataExtendedResponseDataRecordCustom' => __DIR__ .'/CashGetOperationDataExtendedResponseDataRecordCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataByExtIdRequestCustom' => __DIR__ .'/CashGetOperationDataByExtIdRequestCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataByExtIdResponseCustom' => __DIR__ .'/CashGetOperationDataByExtIdResponseCustom.php',
        'jRazer\Wooppay\WSDL\CashGetOperationDataByExtIdResponseDataCustom' => __DIR__ .'/CashGetOperationDataByExtIdResponseDataCustom.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_3bbe6080c1add3551ae900bc9ce6e9a2');

// Do nothing. The rest is just leftovers from the code generation.
{
}
